In [153]:
import pandas as pd

from bike_rental.defs.assets import constants
from bike_rental.defs.assets.helper import data_import_csv, data_merger

In [121]:
bike_rental_data = pd.read_csv(constants.F_BIKE_RENTALS)
direct_pick_up_data = pd.read_csv(constants.F_BIKE_RENTALS_DIRECT_PICKUP)

bike_rental_data.head()

   id             datetime  user_id  location_id
0   1  2011-01-01 00:05:09      158           16
1   2  2011-01-01 00:05:21      262           18
2   3  2011-01-01 00:05:39       68           18
3   4  2011-01-01 00:12:05       12            9
4   5  2011-01-01 00:25:58       91           11

In [122]:
bike_rental_data.tail()

              id             datetime  user_id  location_id
2672657  2672658  2012-12-31 23:53:45      140            1
2672658  2672659  2012-12-31 23:54:01      191           17
2672659  2672660  2012-12-31 23:55:03      283            5
2672660  2672661  2012-12-31 23:55:41      137           16
2672661  2672662  2012-12-31 23:55:53      105           17

In [123]:
direct_pick_up_data.head()

   id             datetime  user_id  location_id
0   1  2011-01-01 00:24:04      232            2
1   2  2011-01-01 00:30:19       54           14
2   3  2011-01-01 00:39:08      201            5
3   4  2011-01-01 01:01:12      298           13
4   5  2011-01-01 01:02:37       23           14

In [124]:
direct_pick_up_data.tail()

            id             datetime  user_id  location_id
620012  620013  2012-12-31 23:30:18      156            6
620013  620014  2012-12-31 23:37:05      119            4
620014  620015  2012-12-31 23:42:35       31           18
620015  620016  2012-12-31 23:44:48       23            5
620016  620017  2012-12-31 23:51:18      165           20

In [125]:
print("Bike Rental Data Shape:", bike_rental_data.shape)
print("Direct Pick Up Data Shape:", direct_pick_up_data.shape)

Bike Rental Data Shape: (2672662, 4)
Direct Pick Up Data Shape: (620017, 4)

In [126]:
bike_rental_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2672662 entries, 0 to 2672661
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   datetime     str
 2   user_id      int64
 3   location_id  int64
dtypes: int64(3), str(1)
memory usage: 81.6 MB

In [127]:
direct_pick_up_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 620017 entries, 0 to 620016
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           620017 non-null  int64
 1   datetime     620017 non-null  str
 2   user_id      620017 non-null  int64
 3   location_id  620017 non-null  int64
dtypes: int64(3), str(1)
memory usage: 18.9 MB

In [128]:
bike_rental_data.describe()

                 id       user_id   location_id
count  2.672662e+06  2.672662e+06  2.672662e+06
mean   1.336332e+06  1.500238e+02  9.994752e+00
std    7.715312e+05  8.690642e+01  6.056529e+00
min    1.000000e+00  0.000000e+00  0.000000e+00
25%    6.681662e+05  7.500000e+01  5.000000e+00
50%    1.336332e+06  1.500000e+02  1.000000e+01
75%    2.004497e+06  2.250000e+02  1.500000e+01
max    2.672662e+06  3.000000e+02  2.000000e+01

In [129]:
direct_pick_up_data.describe()

                  id        user_id    location_id
count  620017.000000  620017.000000  620017.000000
mean   310009.000000     150.064289       9.987275
std    178983.635264      86.885523       6.059862
min         1.000000       0.000000       0.000000
25%    155005.000000      75.000000       5.000000
50%    310009.000000     150.000000      10.000000
75%    465013.000000     225.000000      15.000000
max    620017.000000     300.000000      20.000000

In [130]:
bike_rental_data["datetime"] = pd.to_datetime(bike_rental_data["datetime"])
df1 = bike_rental_data.set_index("datetime")
hourly1 = (
    df1.groupby("location_id").resample("1h").size().reset_index(name="count")
)
hourly1.head()

   location_id            datetime  count
0            0 2011-01-01 01:00:00      1
1            0 2011-01-01 02:00:00      1
2            0 2011-01-01 03:00:00      0
3            0 2011-01-01 04:00:00      0
4            0 2011-01-01 05:00:00      0

In [131]:
hourly1.tail()

        location_id            datetime  count
368390           20 2012-12-31 18:00:00     10
368391           20 2012-12-31 19:00:00      1
368392           20 2012-12-31 20:00:00      5
368393           20 2012-12-31 21:00:00      5
368394           20 2012-12-31 22:00:00      1

In [132]:
direct_pick_up_data["datetime"] = pd.to_datetime(
    direct_pick_up_data["datetime"]
)
df2 = direct_pick_up_data.set_index("datetime")
hourly2 = (
    df2.groupby("location_id").resample("1h").size().reset_index(name="count")
)
hourly2.head()

   location_id            datetime  count
0            0 2011-01-01 03:00:00      2
1            0 2011-01-01 04:00:00      0
2            0 2011-01-01 05:00:00      0
3            0 2011-01-01 06:00:00      0
4            0 2011-01-01 07:00:00      0

In [133]:
hourly2.tail()

        location_id            datetime  count
368275           20 2012-12-31 19:00:00      1
368276           20 2012-12-31 20:00:00      0
368277           20 2012-12-31 21:00:00      0
368278           20 2012-12-31 22:00:00      0
368279           20 2012-12-31 23:00:00      1

In [134]:
merged_hourly = hourly1.merge(
    hourly2,
    on=["datetime", "location_id"],
    how="outer",
    suffixes=("_rentals", "_pickups"),
)

In [135]:
merged_hourly[merged_hourly["location_id"] == 2].head()

    location_id            datetime  count_rentals  count_pickups
0             2 2011-01-01 00:00:00            NaN            1.0
13            2 2011-01-01 01:00:00            2.0            1.0
34            2 2011-01-01 02:00:00            2.0            0.0
55            2 2011-01-01 03:00:00            0.0            0.0
76            2 2011-01-01 04:00:00            0.0            0.0

In [136]:
merged_hourly.fillna(0, inplace=True)
merged_hourly.head()

   location_id   datetime  count_rentals  count_pickups
0            2 2011-01-01            0.0            1.0
1            3 2011-01-01            1.0            0.0
2            4 2011-01-01            2.0            0.0
3            5 2011-01-01            0.0            1.0
4            9 2011-01-01            1.0            0.0

In [154]:
merged_hourly["total_count"] = (
    merged_hourly["count_rentals"] + merged_hourly["count_pickups"]
)
merged_hourly.head()

,location_id,datetime,count_rentals,count_pickups,total_count,weekday,is_weekend,year,month,day,hour,quarter,is_month_start,is_month_end,time_of_day_night,time_of_day_morning,time_of_day_afternoon,time_of_day_evening,time_of_day
0,2,2011-01-01,0.0,1.0,1.0,5,1,2011,1,1,0,1,1,0,1,0,0,0,night
1,3,2011-01-01,1.0,0.0,1.0,5,1,2011,1,1,0,1,1,0,1,0,0,0,night
2,4,2011-01-01,2.0,0.0,2.0,5,1,2011,1,1,0,1,1,0,1,0,0,0,night
3,5,2011-01-01,0.0,1.0,1.0,5,1,2011,1,1,0,1,1,0,1,0,0,0,night
4,9,2011-01-01,1.0,0.0,1.0,5,1,2011,1,1,0,1,1,0,1,0,0,0,night

In [138]:
# Pandas use ISO weekday where Monday is 0 and Sunday is 6
merged_hourly["weekday"] = merged_hourly["datetime"].dt.weekday
merged_hourly.weekday.value_counts()

weekday
6    52920
0    52918
5    52910
1    52416
2    52416
3    52416
4    52416
Name: count, dtype: int64

In [139]:
merged_hourly.tail()

,location_id,datetime,count_rentals,count_pickups,total_count,weekday
368407,16,2012-12-31 23:00:00,2.0,0.0,2.0,0
368408,17,2012-12-31 23:00:00,4.0,0.0,4.0,0
368409,18,2012-12-31 23:00:00,3.0,1.0,4.0,0
368410,19,2012-12-31 23:00:00,0.0,1.0,1.0,0
368411,20,2012-12-31 23:00:00,0.0,1.0,1.0,0

In [140]:
merged_hourly["is_weekend"] = merged_hourly["weekday"].isin([5, 6]).astype(int)
merged_hourly.head()

,location_id,datetime,count_rentals,count_pickups,total_count,weekday,is_weekend
0,2,2011-01-01,0.0,1.0,1.0,5,1
1,3,2011-01-01,1.0,0.0,1.0,5,1
2,4,2011-01-01,2.0,0.0,2.0,5,1
3,5,2011-01-01,0.0,1.0,1.0,5,1
4,9,2011-01-01,1.0,0.0,1.0,5,1

In [146]:
merged_hourly["year"] = merged_hourly["datetime"].dt.year
merged_hourly["month"] = merged_hourly["datetime"].dt.month
merged_hourly["day"] = merged_hourly["datetime"].dt.day
merged_hourly["hour"] = merged_hourly["datetime"].dt.hour
merged_hourly["quarter"] = merged_hourly["datetime"].dt.quarter
merged_hourly["is_month_start"] = merged_hourly[
    "datetime"
].dt.is_month_start.astype(int)
merged_hourly["is_month_end"] = merged_hourly[
    "datetime"
].dt.is_month_end.astype(int)
merged_hourly["time_of_day"] = pd.cut(
    merged_hourly["hour"],
    bins=[0, 6, 12, 18, 24],
    labels=["night", "morning", "afternoon", "evening"],
    right=False,
)

In [142]:
merged_hourly.head()

,location_id,datetime,count_rentals,count_pickups,total_count,weekday,is_weekend,year,month,day,hour,quarter,is_month_start,is_month_end,time_of_day
0,2,2011-01-01,0.0,1.0,1.0,5,1,2011,1,1,0,1,1,0,night
1,3,2011-01-01,1.0,0.0,1.0,5,1,2011,1,1,0,1,1,0,night
2,4,2011-01-01,2.0,0.0,2.0,5,1,2011,1,1,0,1,1,0,night
3,5,2011-01-01,0.0,1.0,1.0,5,1,2011,1,1,0,1,1,0,night
4,9,2011-01-01,1.0,0.0,1.0,5,1,2011,1,1,0,1,1,0,night

In [155]:
merged_hourly = pd.get_dummies(
    merged_hourly, columns=["time_of_day"], dtype=int
)
merged_hourly.head()

,location_id,datetime,count_rentals,count_pickups,total_count,weekday,is_weekend,year,month,day,...,is_month_start,is_month_end,time_of_day_night,time_of_day_morning,time_of_day_afternoon,time_of_day_evening,time_of_day_night,time_of_day_morning,time_of_day_afternoon,time_of_day_evening
0,2,2011-01-01,0.0,1.0,1.0,5,1,2011,1,1,...,1,0,1,0,0,0,1,0,0,0
1,3,2011-01-01,1.0,0.0,1.0,5,1,2011,1,1,...,1,0,1,0,0,0,1,0,0,0
2,4,2011-01-01,2.0,0.0,2.0,5,1,2011,1,1,...,1,0,1,0,0,0,1,0,0,0
3,5,2011-01-01,0.0,1.0,1.0,5,1,2011,1,1,...,1,0,1,0,0,0,1,0,0,0
4,9,2011-01-01,1.0,0.0,1.0,5,1,2011,1,1,...,1,0,1,0,0,0,1,0,0,0

In [144]:
weather_data = data_import_csv(constants.F_WEATHER)
weather_data.drop(columns=["id"], inplace=True)
weather_data["datetime"] = pd.to_datetime(weather_data["datetime"])
weather_data = pd.get_dummies(weather_data, columns=["conditions"], dtype=int)
merged_data = data_merger(
    merged_hourly,
    weather_data,
    on_cols=["datetime"],
    how_to="left",
    suffixe_str=("", "_weather"),
)

In [145]:
merged_data

,location_id,datetime,count_rentals,count_pickups,total_count,weekday,is_weekend,year,month,day,...,time_of_day_afternoon,time_of_day_evening,temperature_c,perceived_temperature_c,humidity,windspeed_kmh,conditions_clear,conditions_clouds,conditions_heavy_rain,conditions_light_rain
0,2,2011-01-01 00:00:00,0.0,1.0,1.0,5,1,2011,1,1,...,0,0,3.3,3.0,81.0,0.0,1.0,0.0,0.0,0.0
1,3,2011-01-01 00:00:00,1.0,0.0,1.0,5,1,2011,1,1,...,0,0,3.3,3.0,81.0,0.0,1.0,0.0,0.0,0.0
2,4,2011-01-01 00:00:00,2.0,0.0,2.0,5,1,2011,1,1,...,0,0,3.3,3.0,81.0,0.0,1.0,0.0,0.0,0.0
3,5,2011-01-01 00:00:00,0.0,1.0,1.0,5,1,2011,1,1,...,0,0,3.3,3.0,81.0,0.0,1.0,0.0,0.0,0.0
4,9,2011-01-01 00:00:00,1.0,0.0,1.0,5,1,2011,1,1,...,0,0,3.3,3.0,81.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368407,16,2012-12-31 23:00:00,2.0,0.0,2.0,0,0,2012,12,31,...,0,1,4.2,2.0,65.0,9.0,1.0,0.0,0.0,0.0
368408,17,2012-12-31 23:00:00,4.0,0.0,4.0,0,0,2012,12,31,...,0,1,4.2,2.0,65.0,9.0,1.0,0.0,0.0,0.0
368409,18,2012-12-31 23:00:00,3.0,1.0,4.0,0,0,2012,12,31,...,0,1,4.2,2.0,65.0,9.0,1.0,0.0,0.0,0.0
368410,19,2012-12-31 23:00:00,0.0,1.0,1.0,0,0,2012,12,31,...,0,1,4.2,2.0,65.0,9.0,1.0,0.0,0.0,0.0
368411,20,2012-12-31 23:00:00,0.0,1.0,1.0,0,0,2012,12,31,...,0,1,4.2,2.0,65.0,9.0,1.0,0.0,0.0,0.0